/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.65
 * Generated at: 2021-04-19 15:48:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/member/join.css\">\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.4.1.js\"\r\n");
      out.write("  integrity=\"sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=\"\r\n");
      out.write("  crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("\t<form id=\"join_form\" method=\"post\">\r\n");
      out.write("\t<div class=\"wrap\">\r\n");
      out.write("\t\t\t<div class=\"subjecet\">\r\n");
      out.write("\t\t\t\t<span>회원가입</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"id_wrap\">\r\n");
      out.write("\t\t\t\t<div class=\"id_name\">아이디</div>\r\n");
      out.write("\t\t\t\t<div class=\"id_input_box\">\r\n");
      out.write("\t\t\t\t\t<input class=\"id_input\" name=\"memberId\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<span class=\"id_input_re_1\">사용 가능한 아이디입니다.</span>\r\n");
      out.write("\t\t\t\t<span class=\"id_input_re_2\">해당 아이디가 이미 존재합니다.</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"pw_wrap\">\r\n");
      out.write("\t\t\t\t<div class=\"pw_name\">비밀번호</div>\r\n");
      out.write("\t\t\t\t<div class=\"pw_input_box\">\r\n");
      out.write("\t\t\t\t\t<input class=\"pw_input\" name=\"memberPw\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"pwck_wrap\">\r\n");
      out.write("\t\t\t\t<div class=\"pwck_name\">비밀번호 확인</div>\r\n");
      out.write("\t\t\t\t<div class=\"pwck_input_box\">\r\n");
      out.write("\t\t\t\t\t<input class=\"pwck_input\" name=\"memberPw\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"user_wrap\">\r\n");
      out.write("\t\t\t\t<div class=\"user_name\">이름</div>\r\n");
      out.write("\t\t\t\t<div class=\"user_input_box\">\r\n");
      out.write("\t\t\t\t\t<input class=\"user_input\" name=\"memberName\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"mail_wrap\">\r\n");
      out.write("\t\t\t\t<div class=\"mail_name\">이메일</div> \r\n");
      out.write("\t\t\t\t<div class=\"mail_input_box\">\r\n");
      out.write("\t\t\t\t\t<input class=\"mail_input\" name=\"memberMail\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"mail_check_wrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"mail_check_input_box\" id=\"mail_check_input_box_false\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"mail_check_input\" disabled=\"disabled\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"mail_check_button\">\r\n");
      out.write("\t\t\t\t\t\t<span>인증번호 전송</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t<span id=\"mail_check_input_box_warn\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"address_wrap\">\r\n");
      out.write("\t\t\t\t<div class=\"address_name\">주소</div>\r\n");
      out.write("\t\t\t\t<div class=\"address_input_1_wrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"address_input_1_box\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"address_input_1\" name=\"memberAddr1\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"address_button\">\r\n");
      out.write("\t\t\t\t\t\t<span>주소 찾기</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class =\"address_input_2_wrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"address_input_2_box\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"address_input_2\" name=\"memberAddr2\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class =\"address_input_3_wrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"address_input_3_box\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"address_input_3\" name=\"memberAddr3\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"join_button_wrap\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" class=\"join_button\" value=\"가입하기\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- \r\n");
      out.write("회원가입 클릭 시 회원가입 기능이 작동하도록 jquery코드 추가\r\n");
      out.write("84번째 줄의 \"가입하기\"버튼 <input type=\"button\" class=\"join_button\" value=\"가입하기\"> 클릭 시 \r\n");
      out.write("form태그의 속성 action이 추가되고(url경로), form태그가 서버에 제출이 된다는 의미. 제출방식은 form태그의 POST형식\r\n");
      out.write(" -->\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var code = \"\"; //Controller(MemberController.java의 mailCheckGET()메소드)로부터 전달받은 인증번호 저장\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t//회원가입 버튼(회원가입 기능 작동)\r\n");
      out.write("\t$(\".join_button\").click(function(){\r\n");
      out.write("\t\t$(\"#join_form\").attr(\"action\", \"/member/join\");\r\n");
      out.write("\t\t$(\"#join_form\").submit();\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write(" * 아이디 중복성 검사\r\n");
      out.write(" */\r\n");
      out.write("$('.id_input').on(\"propertychange change keyup paste input\", function(){\r\n");
      out.write("\tvar memberId = $('.id_input').val(); // .id_input에 입력되는 값을 memberId에 저장\r\n");
      out.write("\tvar data = {memberId : memberId} // 컨트롤에 넘길 데이터 이름 : 데이터(.id_input에 입력된 값)\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype: \"post\",\r\n");
      out.write("\t\turl: \"/member/memberIdChk\",\r\n");
      out.write("\t\tdata: data,\r\n");
      out.write("\t\tsuccess: function(result){\r\n");
      out.write("\t\t\tif(result != 'fail'){\r\n");
      out.write("\t\t\t\t$('.id_input_re_1').css(\"display\",\"inline-block\");\r\n");
      out.write("\t\t\t\t$('.id_input_re_2').css(\"display\",\"none\");\r\n");
      out.write("\t\t\t} else{\r\n");
      out.write("\t\t\t\t$('.id_input_re_2').css(\"display\",\"inline-block\");\r\n");
      out.write("\t\t\t\t$('.id_input_re_1').css(\"display\",\"none\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} //success 종료\r\n");
      out.write("\t}); //ajax 종료\r\n");
      out.write("}); //function 종료\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write(" * 인증번호 이메일 전송\r\n");
      out.write(" */\r\n");
      out.write("$(\".mail_check_button\").click(function(){ //.mail_check_button태그를 갖는 것을 .click 클릭하면 function() 함수 실행\r\n");
      out.write("\t\r\n");
      out.write("\tvar email = $(\".mail_input\").val(); //사용자가 입력한 이메일\r\n");
      out.write("\tvar checkBox = $(\".mail_check_input\"); //인증번호 입력란\r\n");
      out.write("\tvar boxWrap = $(\".mail_check_input_box\"); //인증번호 입력란 박스\r\n");
      out.write("\t$.ajax({//이메일 인증번호 전송을 요청하는 ajax\r\n");
      out.write("\t\ttype:\"GET\", //url을 통해 데이터를 보낼 수 있도록 GET 방식으로 요청 , url명은 Controller의 매핑에 맞게 mailCheck로 설정\r\n");
      out.write("\t\turl:\"mailCheck?email=\" + email, //? 쿼리 요청 시 입력된 email을 집어넣음\r\n");
      out.write("\t\tsuccess:function(data){// ajax 성공 시 해당 함수 실행\r\n");
      out.write("\t\t\tcheckBox.attr(\"disabled\", false); //입력란에 입력가능하도록 속성을 변경 disabled -> false\r\n");
      out.write("\t\t\tboxWrap.attr(\"id\", \"mail_check_input_box_true\"); //입력란의 색상이 변경되도록 회색-> 흰색이 되도록\r\n");
      out.write("\t\t\tcode = data;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write(" * 인증번호 비교\r\n");
      out.write(" */\r\n");
      out.write("$(\".mail_check_input\").blur(function(){\r\n");
      out.write("\tvar inputCode = $(\".mail_check_input\").val();//사용자 입력 코드\r\n");
      out.write("\tvar checkResult = $(\"#mail_check_input_box_warn\"); //비교 결과 span태그의 일치, 불일치\r\n");
      out.write("\t\r\n");
      out.write("    if(inputCode == code){                            // 일치할 경우\r\n");
      out.write("        checkResult.html(\"인증번호가 일치합니다.\");\r\n");
      out.write("        checkResult.attr(\"class\", \"correct\");        \r\n");
      out.write("    } else {                                            // 일치하지 않을 경우\r\n");
      out.write("        checkResult.html(\"인증번호를 다시 확인해주세요.\");\r\n");
      out.write("        checkResult.attr(\"class\", \"incorrect\");\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
